FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/JWTAuthentication.API/JWTAuthentication.API.csproj", "src/JWTAuthentication.API/"]
RUN dotnet restore "./src/JWTAuthentication.API/JWTAuthentication.API.csproj"
COPY . .
WORKDIR "/src/src/JWTAuthentication.API"
RUN dotnet build "./JWTAuthentication.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./JWTAuthentication.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "JWTAuthentication.API.dll"]